version: '3.8'

services:
  backend1:
    build: .
    ports:
      - "1111:8000"
    env_file: .env

  backend2:
    build: .
    ports:
      - "2222:8000"
    env_file: .env

  backend3:
    build: .
    ports:
      - "3333:8000"
    env_file: .env

  backend4:
    build: .
    ports:
      - "4444:8000"
    env_file: .env